---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

RMenu.Add('showcase', 'main', RageUI.CreateMenu("RageUI", "Undefined for using SetSubtitle"))
RMenu:Get('showcase', 'main'):SetSubtitle("~b~RAGEUI SHOWCASE")
RMenu:Get('showcase', 'main').EnableMouse = true
RMenu:Get('showcase', 'main').Closed = function()
    -- TODO Perform action
end;

RMenu.Add('showcase', 'submenu', RageUI.CreateSubMenu(RMenu:Get('showcase', 'main'), "RageUI", "~b~RAGEUI SHOWCASE", nil, nil, "root_cause", "shopui_title_dynasty8"))
RMenu:Get('showcase', 'submenu').EnableMouse = true
RMenu:Get('showcase', 'submenu').Closed = function()
    -- TODO Perform action
end;

RMenu.Add('submenu', 'badges', RageUI.CreateSubMenu(RMenu:Get('showcase', 'main'), "RageUI", "~b~RageUI.BadgeStyle"))
---@type table
local rageui_style = {
    "RageUI",
    "NativeUI",
}

local rageui_cursor = {
    { Name = "None", Value = 0 },
    { Name = "Normal", Value = 1 },
    { Name = "TransparentNormal", Value = 2 },
    { Name = "PreGrab", Value = 3 },
    { Name = "Grab", Value = 4 },
    { Name = "MiddleFinger", Value = 5 },
    { Name = "LeftArrow", Value = 6 },
    { Name = "RightArrow", Value = 7 },
    { Name = "UpArrow", Value = 8 },
    { Name = "DownArrow", Value = 9 },
    { Name = "HorizontalExpand", Value = 10 },
    { Name = "Add", Value = 11 },
    { Name = "Remove", Value = 12 },
}

local index = {
    ketchup = false;
    dish = 1;
    cursor = 1,
    quantity = 0;
    panel = {
        percentage = 0.5
    },
    colored = { [1] = 1, [2] = 1 }
}

local HeritageShape = {
    h = 0.5,
    i = 5
}

---@type string
local description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";

RageUI.CreateWhile(1.0, RMenu:Get('showcase', 'main'), 0xDFF812F9, function()

    RageUI.IsVisible(RMenu:Get('showcase', 'main'), true, true, true, function()
        --- Items
        for i = 1, 100 do
            RageUI.ButtonWithStyle("Cook ! - " .. i, "Cook the dish with the appropriate ingredients and ketchup.", { RightBadge = RageUI.BadgeStyle.Tick }, true, function(Hovered, Active, Selected)
                if (Selected) then

                end
            end)
        end

    end, function()
        ---Panels
    end)

    RageUI.IsVisible(RMenu:Get('showcase', 'submenu'), false, false, true, function()
        --- Items
        for i = 1, 100 do
            RageUI.Button(string.format("Items - %s", i), description, true, function(Hovered, Active, Selected)
                if (Selected) then

                end
            end)
        end
    end, function()
        ---Panels
    end)
end)

